using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace BeehiveManagementSystem
{
    public partial class Form1 : Form
    {
        Queen queen;
        public Form1()
        {
            InitializeComponent();
            workerBeeJob.SelectedIndex = 0;
            Worker[] workers = new Worker[4];
            workers[0] = new Worker(new string[] { "Nectar Collector", "Honey Manufacturing" });
            workers[1] = new Worker(new string[] { "Egg Care", "Baby Bee Tutoring" });
            workers[2] = new Worker(new string[] { "Nectar Collector", "Honey Manufacturing" });
            workers[3] = new Worker(new string[] { "Nectar Collector", "Honey Manufacturing", 
                         "Egg Care", "Baby Bee Tutoring", "Hive Maintenance", "Sting Patrol" });
           queen = new Queen(workers);
        }

        private void button2_Click(object sender, EventArgs e)
        {
            queen.AssignWork(workerBeeJob.SelectedItem.ToString(), (int)shifts.Value);
        }

        private void nextShift_Click(object sender, EventArgs e)
        {
            Queen.WorkTheNextShift();
          
            // Create a new method that takes the strings generated by
            // the WorkTheNextShift() method and outputs them to the 
            // textbox.

            DisplayShiftReport();
        }
        private void DisplayShiftReport()
        {
            string currentDisplay = Queen.WorkTheNextShift();
            textBox1.Text = currentDisplay;
        }

        }
}
