using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace BeehiveManagementSystem
{
    public partial class Form1 : Form
    {
        Queen queen;
        public Form1()
        {
            InitializeComponent();
            workerBeeJob.SelectedIndex = 0;
            Worker[] workers = new Worker[4];
            workers[0] = new Worker(new string[] { "Nectar Collector", "Honey Manufacturing" }, 175);
            workers[1] = new Worker(new string[] { "Egg Care", "Baby Bee Tutoring" }, 114);
            workers[2] = new Worker(new string[] { "Nectar Collector", "Honey Manufacturing" }, 149);
            workers[3] = new Worker(new string[] { "Nectar Collector", "Honey Manufacturing", 
                         "Egg Care", "Baby Bee Tutoring", "Hive Maintenance", "Sting Patrol" }, 155);
           queen = new Queen(workers, 275);
        }

        private void assignWork_Click(object sender, EventArgs e)
        {
            if (queen.AssignWork(workerBeeJob.SelectedItem.ToString(), (int)shifts.Value) == false)
                MessageBox.Show("No workers are available to do the job ' " + workerBeeJob.Text + "' ",
                    "The Queen bee says...");
            else
                MessageBox.Show("The job '" + workerBeeJob.Text + "' will be done in " + shifts.Value + " shifts", "The Queen bee says...");
        }

        private void nextShift_Click(object sender, EventArgs e)
        {
          
            // Create a new method that takes the strings generated by
            // the WorkTheNextShift() method and outputs them to the 
            // textbox.

            report.Text = queen.WorkTheNextShift();
        }
        
        // Creating this reference to the method is unecessary.
        //
        // We can just directly attach it to the form control.
        //
        //private void DisplayShiftReport()
        //{
           
        //    report.Text = queen.WorkTheNextShift();
        //}

        }
}
